### ISSUE TITLE
NanNew(const char*&, std::size_t&)

### ISSUE THREAD

**Issue by jonathanong** [rvagg/nan#227]
i made a module with the async progress worker PR. when trying to upgrade, i get the following compilation error:

```
In member function ‘virtual void TrackWorker::HandleProgressCallback(const char*, std::size_t)’:
error: no matching function for call to ‘NanNew(const char*&, std::size_t&)’
```

My code looks like this:

```cpp
    void HandleProgressCallback(const char *data, size_t size) {
      NanScope();

      Handle<Value> argv[1];

      argv[0] = NanNew(data, size);

      progress->Call(1, argv);
    }
```

i'm assuming this is caused by the `NanNew` rewrite. what's the correct way to do this?

**Comment by kkoopa** [comment]
Try casting `size_t` to `int` and see if that helps. V8 unfortunately uses int wherever the proper way would be to use `size_t`, so truncation (and possible sign overflow) will happen no matter what. Basically, a v8 string cannot be longer than 2^31 - 1 chars, probably even less than that in practice.

**Comment by jonathanong** [comment]
well my strings are like 30 characters long, so it shouldn't be a problem.

```cpp
void HandleProgressCallback(const char *data, size_t size) {
      NanScope();

      Handle<Value> argv[1];

      argv[0] = NanNew(data, (int)size);

      progress->Call(1, argv);
    }
```

```
In member function ‘virtual void TrackWorker::HandleProgressCallback(const char*, std::size_t)’:
error: no matching function for call to ‘NanNew(const char*&, int)’
```

**Comment by jonathanong** [comment]
btw my results look like this:

```js
{a: 1}CVU�B�������Aq
```

i'm just going to truncate the strings at the last `}` in JS land until we figure this out

**Comment by kkoopa** [comment]
Hmm.. Maybe maybe the cast was unnecessary then? What if you make it explicit that you want a String? `NanNew<Strring>(data, size)` Could be that it can't infer that a `String` should be created, because it is being assigned to a `Value`.

**Comment by jonathanong** [comment]
```cpp
    void HandleProgressCallback(const char *data, size_t size) {
      NanScope();

      Handle<Value> argv[1];

      argv[0] = NanNew<String>(data, size);

      progress->Call(1, argv);
    }
```

tried it with and without `,size`. both times got:

```
make: Entering directory `/vagrant/build'
  CXX(target) Release/obj.target/shaheen/node_src/Shaheen.o
In member function ‘virtual void TrackWorker::HandleProgressCallback(const char*, std::size_t)’:
error: parse error in template argument list
       argv[0] = NanNew<String>(data);
                 ^
error: no matching function for call to ‘NanNew(const char*&)’
       argv[0] = NanNew<String>(data);
```

**Comment by kkoopa** [comment]
Summoning @agnat.

**Comment by kkoopa** [comment]
I really don't know what it is acting up right now. Similar constructs are tested in many locations, e.g. https://github.com/rvagg/nan/blob/master/test/cpp/nannew.cpp#L352

**Comment by agnat** [comment]
Ok, that's... odd. @jonathanong, is the code public? If possible I'd like to take a look. Also, what compiler/OS/node version are you using?

Could you take a second and fire up the nan test suite?

````sh
$ cd $NAN_DIR
$ npm run-script rebuild-tests
````

> btw my results look like this: [...]

Not sure I'm following. How, can you get a result if the compilation fails?

**Comment by jonathanong** [comment]
@agnat if you look above, i just removed the `size` parameter from `NanNew` and it works. the problem is that it adds extra characters to the v8 string, so i can just truncate the string in JS land.

it's private but i can send you a gist. won't be compilable on your machine though. can you give me an email or something?

**Comment by agnat** [comment]
Ok, I see. Let's see what we can do without it...

In fact we don't have `NanNew(const char *, int)`. Maybe I lost it in the rewrite. If we had it before we should add it back.

(You should not ignore the size parameter. The `data` argument is clearly not zero terminated and the program reads uninitialized memory. Truncating in JS is not an option.)

Now it gets a bit bizarre:

````
make: Entering directory `/vagrant/build'
  CXX(target) Release/obj.target/shaheen/node_src/Shaheen.o
In member function ‘virtual void TrackWorker::HandleProgressCallback(const char*, std::size_t)’:
error: parse error in template argument list
       argv[0] = NanNew<String>(data);
````

Parse error? This is odd. Is it possible that `String` is something unexpected in this compilation unit? A macro? Do you use `String` anywhere else in this cpp file?

I also totally don't get this one:
````
error: no matching function for call to ‘NanNew(const char*&)’
       argv[0] = NanNew<String>(data);
````

Is that the same line in a different build? Where are the line numbers? Please keep the error messages intact even when anonymizing file names. The error message does not match the code shown. Is this a paste error?

**Comment by rvagg** [comment]
eeek, perhaps replace it with `v8::String` and see what happens.

**Comment by kkoopa** [comment]
Maybe it has to be `v8::String`, if neither `using v8::String` or `using namespace v8` has been declared?

**Comment by agnat** [comment]
Of course. But then all the _other_ code (Handle, Value, &c.) are unqualified too. So, I assume that `using namespace v8` is in effect. But yes, a missing `using v8::String` might be the cause...

**Comment by agnat** [comment]
And: If it is a macro using `v8::String` doesn't help. It just gives more confusing compiler errors. ;)

**Comment by jonathanong** [comment]
i was just trying to replace it with different things as suggested above. i originally had `NanNew(const char *, size_t)`, which worked in the progress worker PR, but does not work in 1.5.0. if i had to guess, it got removed in the rewrite.

**Comment by jonathanong** [comment]
i.e. before, i could just pass the variables in `void HandleProgressCallback(const char *data, size_t size) {` to `NanNew` and everything worked

**Comment by kkoopa** [comment]
Am I missing something here?
https://github.com/rvagg/nan/blob/master/nan_new.h#L130
https://github.com/rvagg/nan/blob/master/nan_implementation_pre_12_inl.h#L150
https://github.com/rvagg/nan/blob/master/nan_implementation_12_inl.h#L153

**Comment by jonathanong** [comment]
are `size_t` and `int` the same?

**Comment by kkoopa** [comment]
Usually not, `size_t` is unsigned, while `int` usually defaults to signed, but the cast I asked you to do first should at least have taken care of that, if it were the problem.

**Comment by jonathanong** [comment]
here's how my code kind of looks right now:

```cpp
void Execute (const NanAsyncProgressWorker::ExecutionProgress& progress) {
      while (true) {
          confidence = tracker.track(frame, outputROI, threshold);
          stringstream ss;
          ss << "{"
            << "\"x\":" << outputROI.x << ","
            << "\"y\":" << outputROI.y << ","
            << "\"width\":" << outputROI.width << ","
            << "\"height\":" << outputROI.height << ","
            << "\"frame\":" << currentFrame << ","
            << "\"confidence\":" << confidence
            << "}";
          string s = ss.str();
          progress.Send(s.c_str(), s.size());
        }
    }

void HandleProgressCallback(const char *data, size_t size) {
      NanScope();

      Handle<Value> argv[1];

      argv[0] = NanNew(data);

      progress->Call(1, argv);
    }

    void HandleOKCallback() {
      NanScope();

      Handle<Value> argv[0];

      callback->Call(0, argv);
    }
```

**Comment by agnat** [comment]
> Am I missing something here? [...]

Well, that is `NanNew<String>(char const*, int)`. The convenience function `NanNew(char const*, int)` is missing around [here](https://github.com/rvagg/nan/blob/master/nan_new.h#L234-L272). 

> are size_t and int the same?

Nope, never. `size_t` is always an unsigned type.

**Comment by jonathanong** [comment]
```cpp
    void HandleProgressCallback(const char *data, size_t size) {
      NanScope();

      Handle<Value> argv[1];

      argv[0] = NanNew<v8::String>(data, size);

      progress->Call(1, argv);
    }
```

this works! i don't know why though.

**Comment by rvagg** [comment]
only a brave engineer asks a C++ compiler _"why"_

**Comment by kkoopa** [comment]
Aha, well then it's settled. Missing convenience function, It did use to exist:
https://github.com/rvagg/nan/blob/v1.4.1/nan.h#L461

**Comment by kkoopa** [comment]
Maybe conflict of two namespaces containing a String class and the perverse using namespace statement?

**Comment by agnat** [comment]
Aha! We're getting closer. I'd bet `String` is a function hence a value hence the parse error... 

Anyway... who's up for re-adding the function? @kkoopa, are you going to do that or do you want a PR?

**Comment by jonathanong** [comment]
@kkoopa i inherited this i don't know what i'm doing

**Comment by kkoopa** [comment]
I can add it and a test, no problem.

@jonathanong It's a case of mistaken identities. Somewhere in your codebase lives something called String. Compiler cannot know if String refers to foo::String or v8::String.

**Comment by kkoopa** [comment]
Note to self: Seems the empty string constructor was also lost in translation.

https://github.com/rvagg/nan/blob/v1.4.1/nan.h#L1274-1277
