### ISSUE TITLE
Error: inline declaration of 'NanNew' follows non-inline definition

### ISSUE THREAD

**Issue by springmeyer** [rvagg/nan#231]
I upgraded [node-mapnik](https://github.com/mapnik/node-mapnik) to nan 1.5.0 today. I also hit https://github.com/rvagg/nan/issues/227 and some of the issues mentioned in #229, but I was able to workaround via changes in node-mapnik easily. And the changes worked fine in older Nan 1.4.1 too, so all good there. Thanks for the great 1.5.0 release.

There is one curious error I'm seeing however that I have not solved. I'd try to look more into this tomorrow and see if I can reduce a testcase.

It only occurs with clang++ 3.5 on travis linux machines (not clang on osx or g++ 4.8 on linux):

```
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew'
      follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_12_inl.h:224:1: note: previous definition
      is here
NanNew(v8::Persistent<T> const& p) {
^
2 errors generated.
```

from https://travis-ci.org/mapnik/node-mapnik/builds/47075698

**Comment by kkoopa** [comment]
I think the problem is that 
https://github.com/rvagg/nan/blob/master/nan_new.h#L165-169 is in the wrong 
location in relation to the forward declarations at 
https://github.com/rvagg/nan/blob/master/nan_new.h#L207-208

The forward declarations have to be before the includes.

**Comment by kkoopa** [comment]
Could also be that the inline keyword is superfluous here 
https://github.com/rvagg/nan/blob/master/nan_new.h#L207-208

Can you try patching and seeing if either helps? It's a bit harder for me to 
reproduce, as I normally don't use clang.

**Comment by springmeyer** [comment]
Just tested @bnoordhuis's fix and I'm now seeing the compile work for clang++ on linux for Node v0.11.14. But not v0.10.33. Perhaps the fix needs to be applied in a second place (https://travis-ci.org/mapnik/node-mapnik/builds/47153780)?

```
../node_modules/nan/nan_new.h:207:43: error: inline declaration of 'NanNew'
      follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: previous
      definition is here
NanNew(v8::Handle<T> h) {
^
In file included from ../src/mapnik_logger.cpp:1:
In file included from ../src/utils.hpp:9:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew'
      follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: previous
      definition is here
NanNew(v8::Persistent<T> const& p) {
^
```

**Comment by bnoordhuis** [comment]
Sorry about that, I thought I tested with v0.10 too.  #235 should address it for good.
