### ISSUE TITLE
Cast v8::Object to v8::Array 

### ISSUE THREAD

**Issue by nicolaspanel** [rvagg/nan#277]
With node#0.10 I used to cast `v8::Value` to `v8::Array`  using the following syntax:

```c
Local<Array> array = Array::Cast(*args[0]->ToObject());
```

Since node#0.11 (or node#0.11) it do not work anymore.

`node-gyp` returns following errors:
```shell
[...]

/home/vagrant/.node-gyp/0.11.16/deps/v8/include/v8.h:390:32: error: 'v8::Local<T>::Local(S*) [with S = v8::Array; T = v8::Array]' is private
   template <class S> V8_INLINE Local(S* that) : Handle<T>(that) { }
                                ^
In file included from ../src/addon.cc:3:0:
[...]: error: within this context
             Local<Array> array = Array::Cast(*args[0]->ToObject());
                                                                  ^
[...]
```

Is there a way to use nan for such conversions?

Best regards

**Comment by bnoordhuis** [comment]
You can use `Local<Array>::Cast(obj)` or just `obj.As<Array>()`.  Either should work with v0.10, v0.12 and io.js.

**Comment by nicolaspanel** [comment]
It works fine. Thanks a lot!
